from django.urls import path
from . import views

urlpatterns=[
    
    path('' , views.picking_plan, name='picking_plan'),
    path('get-messages/', views.get_messages_view, name='get_messages'),
    path('get_combined_data/', views.get_combined_data, name='get_combined_data'),
    path('getPayloadData/', views.get_Payload_Data, name='get_payload_data'),
    path('kitting_in_process/', views.kitting_in_process , name ='kitting_in_process'),
    path('open_modal/', views.open_modal, name='open_modal'),
    path('render_modal/', views.render_modal, name='render_modal'),
    path('enter-key/', views.enter_key, name='enter_key'),
    path('completed_kittings/', views.completed_kittings, name='completed_kittings'),
    path('complete_asn/', views.kitting_config, name='kitting_config'),
    path('asn_input/', views.asn_input, name='asn_input'),
    path('vc_list/', views.vc_list, name='vc_list'),
    path('fetch-existing-vc-entries/', views.fetch_existing_vc_entries, name='fetch_existing_vc_entries'),
    path('update-vc/', views.update_vc, name='update_vc'),
     path('edit_vc/<int:id>/', views.edit_vc, name='edit_vc'),
     path('add-esl-part/', views.add_esl_part, name='add_esl_part'),
    path('delete_vc/<str:part_no>/', views.delete_vc, name='delete_vc'),
     path('upload-excel/', views.upload_excel, name='upload_excel'),
    path('upload-esl-excel/', views.upload_esl_excel, name='upload_esl_excel'), 
     path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('download-sample-excel/', views.download_sample_excel, name='download_sample_excel'),
    path('delete_vc_master/<int:id>/', views.delete_vc_master, name='delete_vc_master'),
     path('add_vc_master/', views.add_vc_master, name='add_vc_master'),
    path('add_trolley_esl/', views.add_trolley_esl, name='add_trolley_esl'),
    path('delete_trolley_esl/', views.delete_trolley_esl, name='delete_trolley_esl'),
    path('model_matrix/', views.base_model_matrix, name='base_model_matrix'),
    path('add_esl_template/', views.add_esl_part_template, name='add_esl_part_template'),
    path('add_new_trolley/', views.add_new_trolley_template, name='add_new_trolley_template'),
    path('vc_model_mapping/', views.vc_model_mapping_template, name='vc_model_mapping_template'),
    path('Part_VC_Map_Data/', views.Part_VC_Map_Data, name='Part_VC_Map_Data'),
    path('esl_update/', views.esl_update, name='esl_update'),
    path("callback/", views.callback_view, name="callback"),
    # path("send_led/", views.send_led_request, name="send_led_request"),
     path('export-vcdatabase/', views.export_vcdatabase_excel, name='export_vcdatabase_excel'),

]
