# Generated by Django 5.0.3 on 2024-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsnSchedule',
            fields=[
                ('master_id', models.AutoField(primary_key=True, serialize=False)),
                ('asn_no', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=5, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('vc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('seq_no', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('selection_status', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_date', models.DateTimeField(blank=True, null=True)),
                ('trar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EslPart',
            fields=[
                ('masterid', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.CharField(blank=True, max_length=5, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('rw', models.IntegerField(blank=True, null=True)),
                ('partno', models.CharField(blank=True, max_length=58, null=True)),
                ('part_desc', models.CharField(blank=True, max_length=58, null=True)),
                ('side', models.CharField(blank=True, max_length=5, null=True)),
                ('tagid', models.CharField(blank=True, max_length=50, null=True)),
                ('tagname', models.CharField(blank=True, max_length=58, null=True)),
                ('tagcode', models.CharField(blank=True, max_length=59, null=True)),
                ('min1', models.IntegerField(blank=True, null=True)),
                ('max1', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VcDatabase',
            fields=[
                ('vc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=5, null=True)),
                ('master_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_no', models.CharField(blank=True, max_length=50, null=True)),
                ('part_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VcMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vcnumber', models.CharField(blank=True, null=True)),
                ('model', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tagid', models.CharField(blank=True, max_length=50, null=True)),
                ('tagcode', models.CharField(blank=True, max_length=50, null=True)),
                ('tagname', models.CharField(blank=True, max_length=50, null=True)),
                ('stdatetime', models.DateTimeField(blank=True, null=True)),
                ('eddatetime', models.DateTimeField(blank=True, null=True)),
                ('asn', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=5, null=True)),
                ('partno', models.CharField(blank=True, max_length=50, null=True)),
                ('partdesc', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('rw', models.IntegerField(blank=True, null=True)),
                ('clan', models.IntegerField(blank=True, null=True)),
                ('statuss', models.IntegerField(blank=True, null=True)),
                ('tror', models.CharField(blank=True, max_length=50, null=True)),
                ('mint', models.IntegerField(blank=True, null=True)),
                ('maxi', models.IntegerField(blank=True, null=True)),
                ('trigtime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
