# Generated by Django 5.0.3 on 2024-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcAndAsn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('asn_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vc_and_asn',
                'managed': False,
            },
        ),
    ]
