# Generated by Django 5.0.3 on 2024-04-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vcandasn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcandasn',
            options={},
        ),
    ]
