# Generated by Django 5.0.3 on 2024-04-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_vcandasn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcandasn',
            options={'managed': False},
        ),
    ]
