# Generated by Django 5.0.3 on 2024-04-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_vcandasn_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcandasn',
            options={},
        ),
    ]
