# Generated by Django 5.0.3 on 2024-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_vcandasn_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcn', models.CharField(blank=True, max_length=50, null=True)),
                ('asnn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
