# Generated by Django 5.0.3 on 2024-04-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='vc_n_asn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_date_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('vcn', models.CharField(blank=True, max_length=50, null=True)),
                ('asnn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
