# Generated by Django 5.0.3 on 2024-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_vc_n_asn_delete_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktable',
            name='statuss',
        ),
        migrations.AddField(
            model_name='worktable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
