# Generated by Django 5.0.3 on 2024-04-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_worktable_statuss_worktable_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asnschedule',
            old_name='trar',
            new_name='trqr',
        ),
    ]
