# Generated by Django 5.0.3 on 2024-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_trar_asnschedule_trqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asnschedule',
            name='selection_status',
            field=models.CharField(choices=[('processing', 'Processing...'), ('completed', 'Completed')], default='Pending...', max_length=20),
        ),
    ]
