# Generated by Django 5.0.3 on 2024-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_asnschedule_selection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='trolley_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('trolley_code', models.CharField(blank=True, max_length=25, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
