# Generated by Django 5.0.3 on 2024-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_trolley_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolley_data',
            name='trolley_picking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
