# Generated by Django 5.0.3 on 2024-06-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_trolley_data_asn_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eslpart',
            old_name='min1',
            new_name='quantity',
        ),
    ]
